### ISSUE TITLE
Tatsumaki Bot goes offline

### ISSUE THREAD

**Issue by Leurisi** [davidlimjh/TatsuBot#1]
I just finished playing my game so I turned my computer off. When I turned my computer back on it came up saying that Tatsumaki is offline.
I am wondering how do I get Tatsumaki back online?

**Comment by jigenator** [comment]
Are you referring to our hosted version of Tatsumaki? 

If so you can join the support Discord server here: https://discordapp.com/invite/0xyZL4m5TyYTzVGY

**Comment by Reubencfernandes** [comment]
link expired
